services:
  kanban-db:
    container_name: kanban-db
    image: postgres:17.2
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - kanban-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  kanban-db-data:
